import type { Metadata } from "next";
import "../styles/globals.css";
import { theme } from "~/styles/theme";
import NavBar from "~/components/navbar";
import { CookiesProvider } from 'next-client-cookies/server';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
 
  return (
    <html lang="en">
      <body className={theme.fonts.ubuntu.className}>
        <NavBar/>
        <CookiesProvider>
          {children}
        </CookiesProvider>
      </body>
    </html>
  );
}
